# RATMS Default Configuration

# Simulation parameters
simulation:
  dt: 0.5                    # Time step in seconds
  duration: 120              # Total simulation time in seconds
  output_data: true          # Enable data output
  output_path: "output.dat"
  roads_path: "roads.dat"

# Logging configuration
logging:
  level: "info"              # debug, info, warning, error
  output: "stdout"           # stdout, stderr, file
  file_path: "ratms.log"

# Traffic light defaults
traffic_lights:
  default_green_time: 30     # seconds
  default_yellow_time: 3     # seconds
  default_red_time: 10       # seconds
  initial_state: "green"     # red, yellow, green

# Vehicle parameters (IDM model)
vehicle:
  default_length: 5.0        # meters
  default_max_speed: 20.0    # m/s (~72 km/h)
  default_aggressivity: 0.5  # 0.0-1.0 scale

  # IDM parameters
  idm:
    desired_time_headway: 1.5      # seconds (T)
    max_acceleration: 2.0          # m/s² (a)
    comfortable_deceleration: 3.0  # m/s² (b)
    min_distance: 2.0              # meters (s0)
    acceleration_exponent: 4.0     # delta

# Road network configuration
network:
  default_lanes: 2
  default_max_speed: 20      # m/s
  min_lane_change_dist: 1.0  # meters
  max_lane_change_dist: 25.0 # meters

# Optimization configuration (GA)
optimization:
  enabled: false
  population_size: 50
  generations: 20
  mutation_rate: 0.1
  crossover_rate: 0.7
  elitism_rate: 0.1
  tournament_size: 3
