# RATMS Development Configuration
# Overrides default.yaml for development environment

simulation:
  duration: 60               # Shorter simulations for testing
  output_data: true

logging:
  level: "debug"             # Verbose logging for development
  output: "stdout"

# Use smaller network for faster iteration
network:
  default_lanes: 2

# Faster optimization for testing
optimization:
  enabled: true
  population_size: 20
  generations: 10
