# RATMS Production Configuration
# Overrides default.yaml for production environment

simulation:
  duration: 3600             # 1 hour simulations
  output_data: true

logging:
  level: "info"
  output: "file"
  file_path: "/var/log/ratms/ratms.log"

# Production-grade optimization
optimization:
  enabled: true
  population_size: 100
  generations: 50
  mutation_rate: 0.05
  crossover_rate: 0.8
